export enum NOTIFICATIONS_ACTION {
  DANGER = 'danger',
  SUCCESS = 'success',
}

export enum NOTIFICATIONS_RESPONSE {
  SUCCESS = '',
  ERROR = 'Response Error',
}

export enum RESET_PASSWORD_PAGES {
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGET_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  SET_PASSWORD = 'SET_PASSWORD',
  RESET_SUCCESSFULLY = 'RESET_SUCCESSFULLY',
}