export enum NOTIFICATIONS_ACTION {
  DANGER = 'danger',
  SUCCESS = 'success',
}

export enum NOTIFICATIONS_RESPONSE {
  SUCCESS = '',
  ERROR = 'Response Error',
}

export enum BOTTOM_WRAPPER_PAGES {
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGET_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  SET_PASSWORD = 'SET_PASSWORD',
  RESET_SUCCESSFULLY = 'RESET_SUCCESSFULLY',
  OPEN = 'OPEN',
  CLOSE = 'CLOSE',
}

export enum QUERY_ENUM {
  ORDER = 'ORDER',
  PRODUCT = 'PRODUCT',
  CATEGORY = "CATEGORY",
  CATEGORY_PRODUCT = "CATEGORY PRODUCT",
  ADDRESS = "ADDRESS",
  CITIES = "CITIES",
  STATES= "STATES",
  WALLET = "WALLET",
  TRANSACTIONHISTORY= "TRANSACTIONHISTORY",
  CREDITHISTORY = "CREDITHISTORY",
  REDEEMCHART= "REDEEMCHART",
  REFERRALS= "REFERRALS"
}